# Generated by Django 3.0.8 on 2020-07-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tumbnail_img',
            new_name='thumbnail_img',
        ),
    ]
